"""Build hardware-komplet.html FROM data/hardware_inventory.json.

Source of truth: data/hardware_inventory.json (sanitized, generated by _build_hardware_inventory.py).
This script only renders HTML — no Homey API access here, no IDs/IPs/tokens.
"""
import sys, io, json, re, html as _html
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
from collections import defaultdict
from pathlib import Path

ROOT = Path(r"C:\Users\lbudi\code\smart-home-website")
INVENTORY_JSON = ROOT / 'data' / 'hardware_inventory.json'

CLASS_LABELS = {
    'sensor': 'Senzor', 'light': 'Světlo', 'socket': 'Zásuvka', 'button': 'Tlačítko',
    'thermostat': 'Termostat / TRV', 'speaker': 'Reproduktor', 'blinds': 'Roleta',
    'airpurifier': 'Čistička', 'vacuumcleaner': 'Robot vysavač', 'tv': 'TV', 'other': 'Ostatní',
}

# Public category label (used in filters)
CATEGORY_LABEL = {
    'sensor': 'Senzory', 'light': 'Světla', 'audio': 'Audio',
    'heating': 'Topení / klima', 'plug': 'Zásuvky', 'button': 'Tlačítka',
    'blind': 'Rolety', 'appliance': 'Spotřebiče', 'infrastructure': 'Infrastruktura',
}

# Load inventory
payload = json.load(open(INVENTORY_JSON, encoding='utf-8'))
items = payload['inventory']
meta = payload['meta']

# Stats
total_devices = meta['total_devices']
zones_real = meta['physical_zones']
by_class = defaultdict(int)
by_category = defaultdict(int)
by_protocol = defaultdict(int)
by_zone = defaultdict(int)
META_ZONES = set(meta['meta_zones_excluded'])
for i in items:
    by_class[i['class']] += 1
    by_category[i['category']] += 1
    if i['protocol'] != 'UNKNOWN':
        by_protocol[i['protocol']] += 1
    if i['zone'] not in META_ZONES and i['zone'] != 'UNKNOWN':
        by_zone[i['zone']] += 1

protocols_used = sorted(by_protocol.keys())

print(f'Loaded inventory: {total_devices} devices, {zones_real} physical zones, {len(protocols_used)} protocols')


CATEGORY_ICON = {
    'sensor': '👁',
    'light': '💡',
    'audio': '🔊',
    'heating': '🌡',
    'plug': '🔌',
    'button': '🎛',
    'blind': '🪟',
    'appliance': '🤖',
    'infrastructure': '🧠',
}


def card_html(it):
    photo_html = ''
    photo_path = it.get('image', '')
    if photo_path and photo_path != 'UNKNOWN':
        local = ROOT / photo_path
        if local.exists():
            photo_html = f'<img src="{photo_path}" alt="{_html.escape(it["model"])}" loading="lazy" />'
    if not photo_html:
        icon = CATEGORY_ICON.get(it.get('category', ''), '📦')
        photo_html = f'<div class="hw-photo-ph"><div class="hw-photo-ph-icon">{icon}</div><div class="hw-photo-ph-text">Foto doplnit</div></div>'

    energy_badge = ''
    if it['energy_data'] == 'REAL':
        energy_badge = '<span class="hw-badge hw-energy-real">⚡ REAL</span>'
    elif it['energy_data'] == 'ESTIMATE':
        energy_badge = '<span class="hw-badge hw-energy-estimate">⚡ ESTIMATE</span>'

    state_badge = f'<span class="hw-badge hw-state-{_html.escape(it["status"])}">{_html.escape(it["status"])}</span>'

    note_html = ''
    if it.get('note'):
        note_html = f'<p class="hw-note-line">{_html.escape(it["note"])}</p>'

    search_blob = (it['name'] + ' ' + it['model'] + ' ' + it['manufacturer'] + ' ' + (it.get('note') or '')).lower()
    class_label = CLASS_LABELS.get(it['class'], it['class'])

    return f'''<article class="hw-card" data-category="{_html.escape(it['category'])}" data-zone="{_html.escape(it['zone'])}" data-protocol="{_html.escape(it['protocol'])}" data-state="{_html.escape(it['status'])}" data-search="{_html.escape(search_blob)}">
  <div class="hw-photo">{photo_html}</div>
  <div class="hw-card-body">
    <h3 class="hw-card-title">{_html.escape(it['public_name'])}</h3>
    <p class="hw-model">{_html.escape(it['manufacturer'])} · {_html.escape(it['model'])}</p>
    {note_html}
    <div class="hw-badges">
      <span class="hw-badge hw-proto">{_html.escape(it['protocol'])}</span>
      <span class="hw-badge hw-cat">{_html.escape(class_label)}</span>
      <span class="hw-badge hw-zone">📍 {_html.escape(it['zone'])}</span>
      {energy_badge}
      {state_badge}
    </div>
  </div>
</article>'''


def stats_card(value, label):
    return f'<div class="hw-stat"><div class="hw-stat-val">{value}</div><div class="hw-stat-lbl">{label}</div></div>'


cards_html = '\n'.join(card_html(it) for it in items)

# Zone table
zone_rows = ''
for zone in sorted(by_zone.keys()):
    devs_in_zone = [i for i in items if i['zone'] == zone]
    devs_by_class = defaultdict(int)
    for d in devs_in_zone:
        devs_by_class[CLASS_LABELS.get(d['class'], d['class'])] += 1
    detail = ', '.join(f"{n}× {lab}" for lab, n in sorted(devs_by_class.items(), key=lambda x: -x[1]))
    zone_rows += f'<tr><td><strong>{_html.escape(zone)}</strong></td><td>{by_zone[zone]}</td><td>{detail}</td></tr>\n'

# Protocol table
PROTO_DESC = {
    'Zigbee': 'Mesh síť, baterie + USB hub. Hlavně senzory, tlačítka, některá světla, Sonoff Zigbee.',
    'Zigbee (Hue Bridge)': 'Philips Hue žárovky přes Hue Bridge.',
    'Z-Wave': 'Stabilní mesh pro kritická zařízení — TRV hlavice, Fibaro motion, kotel relé.',
    'Wi-Fi': 'Spotřebiče (čistička, vysavač, HP tiskárna, kamery Foscam, AndroidTV).',
    'Wi-Fi (Cloud)': 'Shelly Plug S přes cloud relay (Pro řada). Měřené zásuvky.',
    'Wi-Fi (HA)': 'Home Assistant bridge — Sun + Person device pro presence.',
    'Matter': 'Nový standard přes Homey Matter bridge. Meross plug + virtuální RGBTW bulby.',
    'Google Cast (Wi-Fi)': 'Google Nest Mini / Hub Max — TTS, briefing, audio scény.',
    'Cloud (web)': 'Yr.no weather forecast feed (text).',
}
proto_rows = ''
for p in protocols_used:
    desc = PROTO_DESC.get(p, '—')
    proto_rows += f'<tr><td><strong>{_html.escape(p)}</strong></td><td>{by_protocol[p]}</td><td>{_html.escape(desc)}</td></tr>\n'

# Big table
table_rows = ''
for it in items:
    cat_lbl = CLASS_LABELS.get(it['class'], it['class'])
    energy_str = it['energy_data'] if it['energy_data'] != 'UNKNOWN' else '—'
    auto_str = it['automation_used']
    table_rows += (
        f'<tr data-category="{_html.escape(it["category"])}" data-zone="{_html.escape(it["zone"])}" data-protocol="{_html.escape(it["protocol"])}" data-state="{_html.escape(it["status"])}">'
        f'<td>{_html.escape(it["public_name"])}</td>'
        f'<td>{_html.escape(cat_lbl)}</td>'
        f'<td>{_html.escape(it["zone"])}</td>'
        f'<td>{_html.escape(it["protocol"])}</td>'
        f'<td>{_html.escape(it.get("note","")[:60])}</td>'
        f'<td>{_html.escape(auto_str)}</td>'
        f'<td>{_html.escape(energy_str)}</td>'
        f'<td>{_html.escape(it["status"])}</td>'
        '</tr>\n')

# Filter options
all_zones = sorted({i['zone'] for i in items if i['zone'] != 'UNKNOWN'})
all_protos = sorted({i['protocol'] for i in items if i['protocol'] != 'UNKNOWN'})
all_categories = sorted({i['category'] for i in items})

zone_options = '\n'.join(f'<option value="{_html.escape(z)}">{_html.escape(z)}</option>' for z in all_zones)
proto_options = '\n'.join(f'<option value="{_html.escape(p)}">{_html.escape(p)}</option>' for p in all_protos)
cat_options = '\n'.join(f'<option value="{_html.escape(c)}">{_html.escape(CATEGORY_LABEL.get(c, c))}</option>' for c in all_categories)

stats_block = f'''
  <div class="hw-stats">
    {stats_card(total_devices, 'zařízení')}
    {stats_card(zones_real, 'zón')}
    {stats_card(len(protocols_used), 'protokolů')}
    {stats_card(by_class.get('sensor', 0), 'senzorů')}
    {stats_card(by_class.get('light', 0), 'světel')}
    {stats_card(by_class.get('speaker', 0), 'reproduktorů')}
    {stats_card(by_class.get('socket', 0), 'zásuvek')}
    {stats_card(by_class.get('thermostat', 0), 'TRV')}
    {stats_card(by_class.get('button', 0), 'tlačítek')}
  </div>'''

# Stitch from index template
index_html = (ROOT / 'index.html').read_text(encoding='utf-8')
m_head_end = index_html.find('</head>')
m_nav_start = index_html.find('<header')
m_nav_end = index_html.find('</header>')
m_footer_start = index_html.rfind('<footer')
m_footer_end = index_html.rfind('</footer>')

head_block = index_html[:m_head_end]
head_block = re.sub(r'<title>[^<]+</title>',
                     '<title>Kompletní hardware chytré domácnosti | SMART HOME Semily</title>',
                     head_block, count=1)
head_block = re.sub(r'<meta name="description" content="[^"]+"',
                     '<meta name="description" content="Přehled reálně používaného hardwaru v projektu SMART HOME: Homey Pro 2026, senzory, světla, topení, audio, zásuvky, rolety, dashboard a infrastruktura. Data z live Homey exportu (read-only)."',
                     head_block, count=1, flags=re.IGNORECASE)
head_block = re.sub(r'<meta property="og:title" content="[^"]+"',
                     '<meta property="og:title" content="Kompletní hardware chytré domácnosti | SMART HOME Semily"',
                     head_block, count=1)
head_block = re.sub(r'<meta property="og:description" content="[^"]+"',
                     '<meta property="og:description" content="79 zařízení, 10 zón, 9 protokolů — reálný hardware SMART HOME v Semilech, generováno z live Homey exportu."',
                     head_block, count=1)

extra_css = '''
<style>
/* ─── Hardware-komplet page (2026-05-11, v2 SSOT) ─────────────── */
.hw-page { max-width:1320px; margin:0 auto; padding:1.5rem 1.25rem 4rem; }
.hw-hero { padding:2rem 0 1.5rem; border-bottom:1px solid rgba(255,255,255,0.08); margin-bottom:1.5rem; }
.hw-hero h1 { font-size:clamp(1.6rem,3vw,2.4rem); margin:0 0 0.5rem; }
.hw-hero p  { opacity:0.85; max-width:780px; }
.hw-source-note { font-size:0.8rem; opacity:0.6; margin-top:0.5rem; }
.hw-source-note code { background:rgba(255,255,255,0.05); padding:0.1rem 0.4rem; border-radius:4px; font-size:0.78rem; }

.hw-stats { display:grid; grid-template-columns:repeat(auto-fit,minmax(110px,1fr)); gap:0.8rem; margin:1.4rem 0 0; }
.hw-stat  { background:rgba(255,255,255,0.04); border:1px solid rgba(255,255,255,0.08); border-radius:12px; padding:1rem 0.6rem; text-align:center; }
.hw-stat-val { font-size:1.6rem; font-weight:700; color:#7cd6ff; }
.hw-stat-lbl { font-size:0.78rem; opacity:0.7; text-transform:uppercase; letter-spacing:0.5px; margin-top:0.25rem; }

.hw-controls { display:flex; flex-wrap:wrap; gap:0.6rem; align-items:center; margin:1.5rem 0 1rem; padding:0.9rem 1rem; background:rgba(255,255,255,0.03); border:1px solid rgba(255,255,255,0.08); border-radius:12px; }
.hw-controls select, .hw-controls input { padding:0.45rem 0.7rem; border-radius:8px; border:1px solid rgba(255,255,255,0.12); background:rgba(255,255,255,0.04); color:inherit; font-size:0.9rem; min-width:130px; }
.hw-controls input { flex:1; min-width:170px; }
.hw-controls label { font-size:0.78rem; opacity:0.7; text-transform:uppercase; letter-spacing:0.5px; }
.hw-count { margin-left:auto; font-size:0.85rem; opacity:0.8; }

.hw-grid { display:grid; grid-template-columns:repeat(auto-fill,minmax(280px,1fr)); gap:1rem; margin-top:1.2rem; }
.hw-card { background:rgba(255,255,255,0.04); border:1px solid rgba(255,255,255,0.08); border-radius:14px; overflow:hidden; display:flex; flex-direction:column; transition:transform 0.15s, border-color 0.15s; }
.hw-card:hover { transform:translateY(-2px); border-color:rgba(124,214,255,0.3); }
.hw-photo { aspect-ratio:16/10; background:rgba(255,255,255,0.06); display:flex; align-items:center; justify-content:center; overflow:hidden; }
.hw-photo img { width:100%; height:100%; object-fit:contain; padding:0.5rem; }
.hw-photo-ph { color:rgba(255,255,255,0.45); font-size:0.8rem; font-style:italic; text-align:center; }
.hw-card-body { padding:0.9rem 1rem 1rem; }
.hw-card-title { font-size:0.98rem; margin:0 0 0.25rem; line-height:1.25; }
.hw-model { font-size:0.78rem; opacity:0.7; margin:0 0 0.5rem; line-height:1.35; }
.hw-note-line { font-size:0.8rem; opacity:0.85; margin:0 0 0.7rem; line-height:1.4; color:#cfeaff; }
.hw-badges { display:flex; flex-wrap:wrap; gap:0.3rem; }
.hw-badge { font-size:0.7rem; padding:0.2rem 0.55rem; border-radius:999px; background:rgba(255,255,255,0.08); border:1px solid rgba(255,255,255,0.1); white-space:nowrap; }
.hw-proto  { background:rgba(124,214,255,0.15); border-color:rgba(124,214,255,0.25); color:#7cd6ff; }
.hw-cat    { background:rgba(255,200,100,0.13); border-color:rgba(255,200,100,0.2); color:#ffc864; }
.hw-zone   { background:rgba(140,255,160,0.10); border-color:rgba(140,255,160,0.2); color:#9cf2a6; }
.hw-energy-real     { background:rgba(255,100,100,0.15); border-color:rgba(255,100,100,0.25); color:#ff8080; }
.hw-energy-estimate { background:rgba(180,140,255,0.13); border-color:rgba(180,140,255,0.2); color:#c8a6ff; }
.hw-state-active { background:rgba(80,200,120,0.13); border-color:rgba(80,200,120,0.2); color:#7cdc94; }
.hw-state-legacy { background:rgba(150,150,150,0.13); border-color:rgba(150,150,150,0.2); color:#a8a8a8; }
.hw-state-planned { background:rgba(255,200,100,0.13); border-color:rgba(255,200,100,0.2); color:#ffc864; }

.hw-section-h2 { margin-top:2.5rem; padding-bottom:0.4rem; border-bottom:1px solid rgba(255,255,255,0.08); font-size:1.3rem; }
.hw-table-wrap { overflow-x:auto; margin-top:0.8rem; border-radius:12px; border:1px solid rgba(255,255,255,0.08); }
.hw-table { width:100%; border-collapse:collapse; font-size:0.88rem; min-width:760px; }
.hw-table th { background:rgba(124,214,255,0.1); padding:0.7rem 0.8rem; text-align:left; font-weight:600; font-size:0.78rem; text-transform:uppercase; letter-spacing:0.5px; border-bottom:1px solid rgba(255,255,255,0.1); }
.hw-table td { padding:0.55rem 0.8rem; border-bottom:1px solid rgba(255,255,255,0.05); }
.hw-table tr:hover td { background:rgba(255,255,255,0.03); }

.hw-note { background:rgba(255,200,100,0.06); border-left:3px solid #ffc864; padding:0.9rem 1.1rem; border-radius:6px; margin:1.5rem 0; font-size:0.88rem; }
.hw-note strong { color:#ffc864; }

@media (max-width: 720px) {
  .hw-controls { flex-direction:column; align-items:stretch; }
  .hw-controls select, .hw-controls input { width:100%; }
  .hw-count { margin-left:0; }
}
</style>
'''

new_head = head_block + extra_css + '\n</head>'
header_block = index_html[m_nav_start:m_nav_end + len('</header>')]
footer_block = index_html[m_footer_start:m_footer_end + len('</footer>')]

body_main = f'''
<main class="hw-page">
  <div class="hw-hero">
    <h1>Kompletní hardware systému SMART HOME</h1>
    <p>Reálný přehled zařízení, senzorů, světel, audio prvků, měření, infrastruktury a řídicí vrstvy v bytě v Semilech.</p>
    <p class="hw-source-note">📊 Zdroj pravdy: <code>data/hardware_inventory.json</code> — generováno z live Homey REST API exportu ({meta['snapshot_date']}), <strong>read-only přístup</strong>, bez device IDs/IP/tokenů.</p>
    {stats_block}
  </div>

  <div class="hw-note">
    <strong>Bezpečnost a transparentnost:</strong> Stránka <strong>nezobrazuje</strong> interní device ID, IP adresy, MAC adresy ani API tokeny.
    Zobrazena jsou pouze obecná data (název v systému, výrobce, model, protokol, zóna, role, automatizace, měření energie). Kamery jsou uvedené jen popisem role — stream není veřejný.
  </div>

  <div class="hw-controls" role="region" aria-label="Filtry hardwaru">
    <label for="hw-cat">Kategorie:
      <select id="hw-cat">
        <option value="">vše</option>
        {cat_options}
      </select>
    </label>
    <label for="hw-zone">Zóna:
      <select id="hw-zone">
        <option value="">vše</option>
        {zone_options}
      </select>
    </label>
    <label for="hw-proto">Protokol:
      <select id="hw-proto">
        <option value="">vše</option>
        {proto_options}
      </select>
    </label>
    <label for="hw-state">Stav:
      <select id="hw-state">
        <option value="">vše</option>
        <option value="active">active</option>
        <option value="legacy">legacy</option>
        <option value="planned">planned</option>
      </select>
    </label>
    <input type="search" id="hw-search" placeholder="Hledat (název, model, výrobce, poznámka)" aria-label="Hledat zařízení" />
    <span class="hw-count"><span id="hw-count-num">{total_devices}</span> z {total_devices}</span>
  </div>

  <section aria-labelledby="hw-grid-h">
    <h2 id="hw-grid-h" class="hw-section-h2">Karty zařízení</h2>
    <div class="hw-grid" id="hw-grid">
{cards_html}
    </div>
  </section>

  <section aria-labelledby="hw-zone-h">
    <h2 id="hw-zone-h" class="hw-section-h2">Hardware podle zón</h2>
    <p style="opacity:0.85; max-width:780px;">Hardware je distribuovaný po reálných obytných zónách. Zóny jako <em>TOPENI</em>, <em>SMART HOME</em>, <em>Home</em> jsou meta-skupiny pro logiku a nepočítají se mezi obytné prostory.</p>
    <div class="hw-table-wrap">
      <table class="hw-table">
        <thead><tr><th>Zóna</th><th>Počet zařízení</th><th>Co tam je</th></tr></thead>
        <tbody>
{zone_rows}        </tbody>
      </table>
    </div>
  </section>

  <section aria-labelledby="hw-proto-h">
    <h2 id="hw-proto-h" class="hw-section-h2">Použité protokoly</h2>
    <div class="hw-table-wrap">
      <table class="hw-table">
        <thead><tr><th>Protokol</th><th>Počet zařízení</th><th>K čemu / co na něm běží</th></tr></thead>
        <tbody>
{proto_rows}        </tbody>
      </table>
    </div>
  </section>

  <section aria-labelledby="hw-table-h">
    <h2 id="hw-table-h" class="hw-section-h2">Detailní tabulka (všechna zařízení)</h2>
    <p style="opacity:0.85;">Filtry nahoře platí i pro tuto tabulku.</p>
    <div class="hw-table-wrap">
      <table class="hw-table" id="hw-table">
        <thead><tr>
          <th>Zařízení</th><th>Kategorie</th><th>Zóna</th><th>Protokol</th><th>Poznámka</th><th>Automat.</th><th>Energie</th><th>Stav</th>
        </tr></thead>
        <tbody>
{table_rows}        </tbody>
      </table>
    </div>
  </section>

  <section>
    <h2 class="hw-section-h2">Odkazy</h2>
    <p><a href="senzory.html">Senzory →</a> · <a href="svetla.html">Světla →</a> · <a href="topeni-klima.html">Topení a klima →</a> · <a href="audio.html">Audio a TTS →</a> · <a href="ovladace.html">Ovladače →</a> · <a href="rolety.html">Rolety →</a> · <a href="zasuvky.html">Zásuvky →</a> · <a href="dashboard.html">Dashboard →</a> · <a href="ai-brain.html">AI Brain →</a></p>
  </section>
</main>

<script>
(function() {{
  const cat=document.getElementById('hw-cat'),
        zone=document.getElementById('hw-zone'),
        proto=document.getElementById('hw-proto'),
        state=document.getElementById('hw-state'),
        search=document.getElementById('hw-search'),
        countEl=document.getElementById('hw-count-num'),
        cards=document.querySelectorAll('#hw-grid .hw-card'),
        rows=document.querySelectorAll('#hw-table tbody tr');
  function apply() {{
    const c=cat.value, z=zone.value, p=proto.value, s=state.value;
    const q=(search.value||'').trim().toLowerCase();
    let shown=0;
    cards.forEach(el => {{
      let ok=true;
      if (c && el.dataset.category!==c) ok=false;
      if (ok && z && el.dataset.zone!==z) ok=false;
      if (ok && p && el.dataset.protocol!==p) ok=false;
      if (ok && s && el.dataset.state!==s) ok=false;
      if (ok && q && (el.dataset.search||'').indexOf(q)<0) ok=false;
      el.style.display = ok?'':'none';
      if (ok) shown++;
    }});
    rows.forEach(el => {{
      let ok=true;
      if (c && el.dataset.category!==c) ok=false;
      if (ok && z && el.dataset.zone!==z) ok=false;
      if (ok && p && el.dataset.protocol!==p) ok=false;
      if (ok && s && el.dataset.state!==s) ok=false;
      if (ok && q && (el.textContent||'').toLowerCase().indexOf(q)<0) ok=false;
      el.style.display = ok?'':'none';
    }});
    countEl.textContent = shown;
  }}
  [cat,zone,proto,state].forEach(el => el.addEventListener('change', apply));
  search.addEventListener('input', apply);
}})();
</script>
'''

final = new_head + '\n<body>\n' + header_block + body_main + footer_block + '\n</body>\n</html>'

out = ROOT / 'hardware-komplet.html'
out.write_text(final, encoding='utf-8')
print(f'OK written: {out} ({len(final)} chars)')
