"""Build hardware-komplet.html (v2 — extended schema, filters, table mode).

Source: data/hardware_inventory_verified.json (generated by _build_hardware_verified.py).
Output: hardware-komplet.html

Features (per OPRAVA_STRANKY_HARDWARE_PROMPT.md):
  - Hero + KPI cards (Total / Zigbee / Z-Wave / Matter / Wi-Fi / Virtual / Energy / Automation)
  - Filters: search + zone + protocol + brand + automation + Matter + energy
  - Card + Table mode toggle
  - Sections: per-zone + Matter/Bridge + UNKNOWN to verify
  - SEO meta + OG
  - Responsive 1920 / 1366 / 390
"""
import sys
import json
import re
import html as _html
from pathlib import Path
from collections import defaultdict, Counter
from datetime import datetime

sys.stdout.reconfigure(encoding='utf-8')

ROOT = Path(r"C:\Users\lbudi\code\smart-home-website")
INV_JSON = ROOT / 'data' / 'hardware_inventory_verified.json'
OUT_HTML = ROOT / 'hardware-komplet.html'
INDEX_HTML = ROOT / 'index.html'

DATE = datetime.now().strftime('%Y-%m-%d')

# ─── Load ──────────────────────────────────────────────────
payload = json.load(open(INV_JSON, encoding='utf-8'))
items = payload['inventory']
meta = payload['meta']

# Stats
total = len(items)
by_proto = Counter(it['protocol'] for it in items)
by_zone = Counter(it['zone'] for it in items)
by_brand = Counter(it['brand'] for it in items)
by_matter = Counter(it['matter_device'] for it in items)
by_verif = Counter(it['verification_status'] for it in items)

# KPI counts
n_zigbee = by_proto.get('Zigbee', 0) + by_proto.get('Zigbee (Hue Bridge)', 0)
n_zwave = by_proto.get('Z-Wave', 0)
n_matter = by_matter.get('yes', 0)
n_wifi = sum(c for p, c in by_proto.items() if 'Wi-Fi' in p)
n_cast = by_proto.get('Google Cast (Wi-Fi)', 0)
n_cloud = sum(c for p, c in by_proto.items() if 'Cloud' in p)
n_virtual = sum(1 for it in items if 'virtual' in (it.get('app', '') or '').lower())
n_energy = sum(1 for it in items if it['energy_measured'] in ('yes', 'partial'))
n_auto = sum(1 for it in items if it['used_in_automation'] == 'yes')
n_dash = sum(1 for it in items if it['used_in_dashboard'] == 'yes')

physical_zones = sorted({it['zone'] for it in items if it['zone'] not in ('nefunkcni', 'UNKNOWN', '')})

# Category icon (fallback when no photo)
ROLE_ICON = {
    'light': '💡', 'sensor': '👁', 'thermostat': '🌡', 'socket': '🔌',
    'button': '🎛', 'speaker': '🔊', 'camera': '📷', 'tv': '📺',
    'windowcoverings': '🪟', 'vacuumcleaner': '🤖', 'heater': '🔥',
    'fan': '🌀', 'curtain': '🪟', 'kettle': '☕', 'coffeemachine': '☕',
    'remote': '🎮', 'other': '📦', 'lock': '🔒', 'doorbell': '🔔',
}


def yn_label(val):
    if val == 'yes':
        return '<span class="hw-yn hw-yes">✓ ano</span>'
    if val == 'no':
        return '<span class="hw-yn hw-no">— ne</span>'
    if val == 'partial':
        return '<span class="hw-yn hw-partial">~ částečně</span>'
    return '<span class="hw-yn hw-unk">? unknown</span>'


def verif_badge(val):
    if val == 'verified':
        return '<span class="hw-badge hw-verif-ok">✅ verified</span>'
    if val == 'partial':
        return '<span class="hw-badge hw-verif-partial">🟡 partial</span>'
    return '<span class="hw-badge hw-verif-unk">❓ unknown</span>'


def matter_badge(matter_class):
    if matter_class == 'physical':
        return '<span class="hw-badge hw-matter-phys">🔷 Matter</span>'
    if matter_class == 'virtual_bridge':
        return '<span class="hw-badge hw-matter-virt">🔶 Matter virtual</span>'
    return ''


def card_html(it):
    img = it.get('image_file', '')
    if img and (ROOT / img).exists():
        photo = f'<img src="{_html.escape(img)}" alt="{_html.escape(it["display_name"])}" loading="lazy" />'
    else:
        icon = ROLE_ICON.get(it['device_class'], '📦')
        photo = (f'<div class="hw-photo-ph">'
                 f'<div class="hw-photo-ph-icon">{icon}</div>'
                 f'<div class="hw-photo-ph-text">Foto k doplnění</div></div>')

    caps_brief = ', '.join(it.get('capabilities', [])[:4])
    if len(it.get('capabilities', [])) > 4:
        caps_brief += f' …+{len(it["capabilities"])-4}'

    matter_b = matter_badge(it.get('matter_class', 'no'))

    search_blob = ' '.join([
        it['name_homey'], it['display_name'], it['brand'], it['model'],
        it['protocol'], it['zone'], it.get('role', ''),
        ' '.join(it.get('capabilities', []))
    ]).lower()

    return f'''<article class="hw-card"
  data-zone="{_html.escape(it['zone'])}"
  data-protocol="{_html.escape(it['protocol'])}"
  data-brand="{_html.escape(it['brand'])}"
  data-class="{_html.escape(it['device_class'])}"
  data-matter="{_html.escape(it['matter_device'])}"
  data-auto="{_html.escape(it['used_in_automation'])}"
  data-energy="{_html.escape(it['energy_measured'])}"
  data-verification="{_html.escape(it['verification_status'])}"
  data-search="{_html.escape(search_blob)}">
  <div class="hw-photo">{photo}</div>
  <div class="hw-card-body">
    <h3 class="hw-card-title">{_html.escape(it['display_name'])}</h3>
    <p class="hw-meta-line"><strong>{_html.escape(it['brand'])}</strong> · {_html.escape(it['model'])}</p>
    <p class="hw-role">{_html.escape(it.get('role','—'))}</p>
    <div class="hw-badges">
      <span class="hw-badge hw-proto">{_html.escape(it['protocol'])}</span>
      <span class="hw-badge hw-zone">📍 {_html.escape(it['zone'])}</span>
      {matter_b}
      {verif_badge(it['verification_status'])}
    </div>
    <dl class="hw-status">
      <div><dt>Automatizace</dt><dd>{yn_label(it['used_in_automation'])}</dd></div>
      <div><dt>Dashboard</dt><dd>{yn_label(it['used_in_dashboard'])}</dd></div>
      <div><dt>Energy</dt><dd>{yn_label(it['energy_measured'])}</dd></div>
    </dl>
    <p class="hw-caps">⚙ {_html.escape(caps_brief) if caps_brief else '—'}</p>
  </div>
</article>'''


def table_row(it):
    matter_lbl = it.get('matter_class', 'no')
    if matter_lbl == 'virtual_bridge':
        matter_lbl = 'virtual'
    elif matter_lbl == 'physical':
        matter_lbl = 'yes'
    return (
        f'<tr data-zone="{_html.escape(it["zone"])}" '
        f'data-protocol="{_html.escape(it["protocol"])}" '
        f'data-brand="{_html.escape(it["brand"])}" '
        f'data-matter="{_html.escape(it["matter_device"])}" '
        f'data-auto="{_html.escape(it["used_in_automation"])}" '
        f'data-energy="{_html.escape(it["energy_measured"])}" '
        f'data-verification="{_html.escape(it["verification_status"])}">'
        f'<td>{_html.escape(it["display_name"])}</td>'
        f'<td>{_html.escape(it["zone"])}</td>'
        f'<td>{_html.escape(it["brand"])}</td>'
        f'<td>{_html.escape(it["model"])}</td>'
        f'<td>{_html.escape(it["protocol"])}</td>'
        f'<td>{matter_lbl}</td>'
        f'<td>{it["used_in_automation"]}</td>'
        f'<td>{it["used_in_dashboard"]}</td>'
        f'<td>{it["energy_measured"]}</td>'
        f'<td>{verif_badge(it["verification_status"])}</td>'
        '</tr>'
    )


# ─── Build sections ────────────────────────────────────────
# Group by zone (skip "nefunkcni" and UNKNOWN; collect them in Tail sections)
zone_order_pref = ['Jídelna', 'Kitchen', 'Spolecne', 'Ložnice', 'Koupelna',
                   'Pracovna', 'Prádelna', 'Předsíň', 'Toaleta', 'Pc Setup']
zones_present = sorted({it['zone'] for it in items if it['zone'] not in ('nefunkcni', 'UNKNOWN', '')})
zones_present_ord = [z for z in zone_order_pref if z in zones_present] + \
                    [z for z in zones_present if z not in zone_order_pref]

# Matter dedicated section
matter_items = sorted([it for it in items if it['matter_device'] == 'yes'],
                      key=lambda x: (x['matter_class'] != 'physical', x['display_name']))

# UNKNOWN / partial section (verification != verified OR brand/model unknown)
unknown_items = [it for it in items
                 if it['verification_status'] != 'verified'
                 or it['brand'] == 'UNKNOWN' or it['model'] == 'UNKNOWN']

# Legacy (zone == nefunkcni)
legacy_items = [it for it in items if it['zone'] in ('nefunkcni',)]

# ─── Stats card render ─────────────────────────────────────
def stats_card(value, label, hue='cyan'):
    return (f'<div class="hw-stat hw-stat-{hue}">'
            f'<div class="hw-stat-val">{value}</div>'
            f'<div class="hw-stat-lbl">{label}</div></div>')


KPI_BLOCK = f'''
<div class="hw-kpis">
  {stats_card(total, 'celkem zařízení', 'cyan')}
  {stats_card(len(physical_zones), 'fyzických zón', 'cyan')}
  {stats_card(n_zigbee, 'Zigbee', 'amber')}
  {stats_card(n_zwave, 'Z-Wave', 'green')}
  {stats_card(n_matter, 'Matter', 'purple')}
  {stats_card(n_wifi + n_cast, 'Wi-Fi / Cast', 'blue')}
  {stats_card(n_cloud, 'Cloud / Web', 'gray')}
  {stats_card(n_energy, 'měří energii', 'red')}
  {stats_card(n_auto, 'v automatizaci', 'green')}
  {stats_card(n_dash, 'v dashboardu', 'cyan')}
</div>
'''


# ─── Filter dropdowns ──────────────────────────────────────
def opts(values, with_count=False):
    out = ['<option value="">vše</option>']
    for v in sorted(values):
        if not v or v == 'UNKNOWN':
            continue
        out.append(f'<option value="{_html.escape(v)}">{_html.escape(v)}</option>')
    return '\n'.join(out)


all_zones = sorted({it['zone'] for it in items if it['zone']})
all_protos = sorted({it['protocol'] for it in items if it['protocol']})
all_brands = sorted({it['brand'] for it in items if it['brand']})

FILTERS_BLOCK = f'''
<div class="hw-controls" role="region" aria-label="Filtry hardwaru">
  <input id="hw-search" type="search" placeholder="🔍 Hledat název, model, capability…" aria-label="Vyhledávání">
  <select id="hw-zone" aria-label="Filtr zóna">{opts(all_zones)}</select>
  <select id="hw-proto" aria-label="Filtr protokol">{opts(all_protos)}</select>
  <select id="hw-brand" aria-label="Filtr výrobce">{opts(all_brands)}</select>
  <select id="hw-matter" aria-label="Filtr Matter">
    <option value="">Matter: vše</option>
    <option value="yes">Matter: ano</option>
    <option value="no">Matter: ne</option>
  </select>
  <select id="hw-auto" aria-label="Filtr automatizace">
    <option value="">Automatizace: vše</option>
    <option value="yes">Automatizace: ano</option>
    <option value="no">Automatizace: ne</option>
  </select>
  <select id="hw-energy" aria-label="Filtr energy">
    <option value="">Energy: vše</option>
    <option value="yes">Energy: ano</option>
    <option value="partial">Energy: částečně</option>
    <option value="no">Energy: ne</option>
  </select>
  <button id="hw-reset" type="button" class="hw-btn-reset">Reset</button>
  <div class="hw-mode-toggle" role="tablist" aria-label="Režim zobrazení">
    <button type="button" id="hw-mode-cards" class="hw-mode-btn hw-mode-active" aria-pressed="true">📇 Karty</button>
    <button type="button" id="hw-mode-table" class="hw-mode-btn" aria-pressed="false">📋 Tabulka</button>
  </div>
  <div class="hw-count"><span id="hw-count-num">{total}</span> / {total} zařízení</div>
</div>
'''


# ─── Sections HTML ─────────────────────────────────────────
def section(title, items_list, anchor_id=''):
    if not items_list:
        return ''
    id_attr = f' id="sec-{anchor_id}"' if anchor_id else ''
    cards = '\n'.join(card_html(it) for it in items_list)
    return (f'<section class="hw-section"{id_attr}>'
            f'<h2 class="hw-section-h2">{_html.escape(title)} '
            f'<span class="hw-section-count">({len(items_list)})</span></h2>'
            f'<div class="hw-grid">{cards}</div></section>')


def section_dup(title, items_list, anchor_id='', is_dup=False):
    """Same as section() but marks cards as duplicates so they don't double-count."""
    if not items_list:
        return ''
    id_attr = f' id="sec-{anchor_id}"' if anchor_id else ''
    if is_dup:
        # Replace `<article class="hw-card"` with `<article class="hw-card hw-card-dup"`
        cards = '\n'.join(card_html(it).replace('class="hw-card"', 'class="hw-card hw-card-dup"', 1)
                         for it in items_list)
    else:
        cards = '\n'.join(card_html(it) for it in items_list)
    return (f'<section class="hw-section"{id_attr}>'
            f'<h2 class="hw-section-h2">{_html.escape(title)} '
            f'<span class="hw-section-count">({len(items_list)})</span></h2>'
            f'<div class="hw-grid">{cards}</div></section>')


CARDS_VIEW = '<div id="hw-view-cards">\n'
# Matter dedicated section first (marked as duplicate — items also appear in their zones)
if matter_items:
    CARDS_VIEW += section_dup(
        f'🔷 Matter / Thread / Bridge zařízení',
        matter_items, anchor_id='matter', is_dup=True)

# Per-zone sections
for z in zones_present_ord:
    z_items = [it for it in items if it['zone'] == z and it not in legacy_items]
    if z_items:
        CARDS_VIEW += section(f'📍 {z}', z_items, anchor_id=f'zone-{z}')

# Legacy
if legacy_items:
    CARDS_VIEW += section('🗄 Legacy / nefunkční zóna', legacy_items, anchor_id='legacy')

# UNKNOWN to verify (also duplicate cards — items appear in zones too)
if unknown_items:
    CARDS_VIEW += section_dup(
        '❓ Zařízení k ověření (UNKNOWN / partial)',
        unknown_items, anchor_id='unknown', is_dup=True)

CARDS_VIEW += '</div>'


# ─── Table view ────────────────────────────────────────────
TABLE_ROWS = '\n'.join(table_row(it) for it in items)
TABLE_VIEW = f'''
<div id="hw-view-table" class="hw-table-wrap" style="display:none;">
  <table class="hw-table">
    <thead>
      <tr>
        <th>Název</th><th>Zóna</th><th>Výrobce</th><th>Model</th>
        <th>Protokol</th><th>Matter</th><th>Auto</th><th>Dash</th>
        <th>Energy</th><th>Ověření</th>
      </tr>
    </thead>
    <tbody>{TABLE_ROWS}</tbody>
  </table>
</div>
'''


# ─── CSS ────────────────────────────────────────────────────
EXTRA_CSS = '''
<style>
/* ─── Hardware-komplet v2 (2026-05-11, OPRAVA_STRANKY_HARDWARE) ── */
.hw-page { max-width:1400px; margin:0 auto; padding:1.5rem 1.25rem 4rem; }

/* HERO */
.hw-hero { padding:2rem 0 1.5rem; border-bottom:1px solid rgba(255,255,255,0.08); margin-bottom:1.5rem; }
.hw-hero h1 { font-size:clamp(1.6rem,3vw,2.4rem); margin:0 0 0.5rem; }
.hw-hero p  { opacity:0.85; max-width:880px; }
.hw-source-note { font-size:0.8rem; opacity:0.6; margin-top:0.5rem; }
.hw-source-note code { background:rgba(255,255,255,0.05); padding:0.1rem 0.4rem; border-radius:4px; font-size:0.78rem; }

/* KPI cards */
.hw-kpis { display:grid; grid-template-columns:repeat(auto-fit,minmax(120px,1fr)); gap:0.7rem; margin:1.5rem 0 0; }
.hw-stat { background:rgba(255,255,255,0.04); border:1px solid rgba(255,255,255,0.08); border-radius:12px; padding:0.9rem 0.5rem; text-align:center; transition:transform 0.15s; }
.hw-stat:hover { transform:translateY(-2px); }
.hw-stat-val { font-size:1.6rem; font-weight:700; }
.hw-stat-lbl { font-size:0.74rem; opacity:0.7; text-transform:uppercase; letter-spacing:0.5px; margin-top:0.2rem; }
.hw-stat-cyan   .hw-stat-val { color:#7cd6ff; }
.hw-stat-amber  .hw-stat-val { color:#ffc864; }
.hw-stat-green  .hw-stat-val { color:#7cdc94; }
.hw-stat-purple .hw-stat-val { color:#c8a6ff; }
.hw-stat-blue   .hw-stat-val { color:#80b0ff; }
.hw-stat-red    .hw-stat-val { color:#ff8080; }
.hw-stat-gray   .hw-stat-val { color:#a8a8a8; }

/* Controls */
.hw-controls { display:flex; flex-wrap:wrap; gap:0.55rem; align-items:center; margin:1.5rem 0 1rem; padding:0.9rem 1rem; background:rgba(255,255,255,0.03); border:1px solid rgba(255,255,255,0.08); border-radius:12px; }
.hw-controls select, .hw-controls input { padding:0.45rem 0.7rem; border-radius:8px; border:1px solid rgba(255,255,255,0.12); background:rgba(255,255,255,0.04); color:inherit; font-size:0.88rem; }
.hw-controls input { flex:1 1 220px; min-width:200px; }
.hw-controls select { min-width:140px; }
.hw-btn-reset { padding:0.45rem 0.9rem; border-radius:8px; border:1px solid rgba(255,255,255,0.15); background:rgba(255,200,100,0.1); color:#ffc864; cursor:pointer; font-size:0.85rem; }
.hw-btn-reset:hover { background:rgba(255,200,100,0.18); }

.hw-mode-toggle { display:inline-flex; border:1px solid rgba(255,255,255,0.12); border-radius:8px; overflow:hidden; }
.hw-mode-btn { padding:0.45rem 0.8rem; background:rgba(255,255,255,0.04); border:0; color:inherit; cursor:pointer; font-size:0.85rem; border-right:1px solid rgba(255,255,255,0.08); }
.hw-mode-btn:last-child { border-right:0; }
.hw-mode-btn.hw-mode-active { background:rgba(124,214,255,0.18); color:#7cd6ff; }
.hw-mode-btn:hover { background:rgba(255,255,255,0.08); }
.hw-count { margin-left:auto; font-size:0.85rem; opacity:0.8; }

/* Note box */
.hw-note { background:rgba(255,200,100,0.06); border-left:3px solid #ffc864; padding:0.9rem 1.1rem; border-radius:6px; margin:1.2rem 0; font-size:0.88rem; }
.hw-note strong { color:#ffc864; }

/* Section */
.hw-section { margin-top:2.5rem; }
.hw-section-h2 { padding-bottom:0.4rem; border-bottom:1px solid rgba(255,255,255,0.08); font-size:1.3rem; display:flex; align-items:baseline; gap:0.6rem; flex-wrap:wrap; }
.hw-section-count { font-size:0.85rem; opacity:0.6; font-weight:normal; }

/* Grid */
.hw-grid { display:grid; grid-template-columns:repeat(auto-fill,minmax(290px,1fr)); gap:1rem; margin-top:1rem; }
.hw-card { background:rgba(255,255,255,0.04); border:1px solid rgba(255,255,255,0.08); border-radius:14px; overflow:hidden; display:flex; flex-direction:column; transition:transform 0.15s, border-color 0.15s; }
.hw-card:hover { transform:translateY(-2px); border-color:rgba(124,214,255,0.3); }
.hw-card.hw-hidden { display:none; }

.hw-photo { aspect-ratio:16/10; background:rgba(255,255,255,0.06); display:flex; align-items:center; justify-content:center; overflow:hidden; }
.hw-photo img { width:100%; height:100%; object-fit:contain; padding:0.5rem; }
.hw-photo-ph { color:rgba(255,255,255,0.45); font-size:0.8rem; font-style:italic; text-align:center; }
.hw-photo-ph-icon { font-size:2.4rem; margin-bottom:0.2rem; opacity:0.7; }
.hw-photo-ph-text { font-size:0.7rem; }

.hw-card-body { padding:0.9rem 1rem 1rem; flex:1; display:flex; flex-direction:column; }
.hw-card-title { font-size:0.98rem; margin:0 0 0.15rem; line-height:1.25; }
.hw-meta-line { font-size:0.78rem; opacity:0.75; margin:0 0 0.3rem; line-height:1.35; }
.hw-meta-line strong { color:#cfeaff; }
.hw-role { font-size:0.74rem; opacity:0.7; margin:0 0 0.5rem; font-style:italic; }

.hw-badges { display:flex; flex-wrap:wrap; gap:0.3rem; margin-bottom:0.6rem; }
.hw-badge { font-size:0.7rem; padding:0.2rem 0.55rem; border-radius:999px; background:rgba(255,255,255,0.08); border:1px solid rgba(255,255,255,0.1); white-space:nowrap; }
.hw-proto  { background:rgba(124,214,255,0.15); border-color:rgba(124,214,255,0.25); color:#7cd6ff; }
.hw-zone   { background:rgba(140,255,160,0.10); border-color:rgba(140,255,160,0.2); color:#9cf2a6; }
.hw-matter-phys { background:rgba(200,166,255,0.18); border-color:rgba(200,166,255,0.3); color:#c8a6ff; }
.hw-matter-virt { background:rgba(255,200,100,0.13); border-color:rgba(255,200,100,0.2); color:#ffc864; }
.hw-verif-ok      { background:rgba(80,200,120,0.13); border-color:rgba(80,200,120,0.2); color:#7cdc94; }
.hw-verif-partial { background:rgba(255,200,100,0.13); border-color:rgba(255,200,100,0.2); color:#ffc864; }
.hw-verif-unk     { background:rgba(150,150,150,0.13); border-color:rgba(150,150,150,0.2); color:#a8a8a8; }

.hw-status { display:grid; grid-template-columns:repeat(3,1fr); gap:0.4rem; margin:0.3rem 0 0.6rem; padding:0.45rem; background:rgba(255,255,255,0.03); border-radius:8px; }
.hw-status > div { text-align:center; }
.hw-status dt { font-size:0.65rem; opacity:0.6; text-transform:uppercase; letter-spacing:0.3px; margin-bottom:0.15rem; }
.hw-status dd { margin:0; font-size:0.72rem; }
.hw-yn { font-weight:600; }
.hw-yn.hw-yes { color:#7cdc94; }
.hw-yn.hw-no { color:#a8a8a8; }
.hw-yn.hw-partial { color:#ffc864; }
.hw-yn.hw-unk { color:#a8a8a8; opacity:0.7; }

.hw-caps { font-size:0.7rem; opacity:0.55; margin:auto 0 0; line-height:1.4; }

/* Table view */
.hw-table-wrap { overflow-x:auto; margin-top:1rem; border-radius:12px; border:1px solid rgba(255,255,255,0.08); }
.hw-table { width:100%; border-collapse:collapse; font-size:0.85rem; min-width:1000px; }
.hw-table th { background:rgba(124,214,255,0.1); padding:0.65rem 0.7rem; text-align:left; font-weight:600; font-size:0.76rem; text-transform:uppercase; letter-spacing:0.5px; border-bottom:1px solid rgba(255,255,255,0.1); position:sticky; top:0; backdrop-filter:blur(8px); }
.hw-table td { padding:0.5rem 0.7rem; border-bottom:1px solid rgba(255,255,255,0.05); }
.hw-table tr:hover td { background:rgba(255,255,255,0.03); }
.hw-table tr.hw-hidden { display:none; }

/* Responsive */
@media (max-width: 1024px) {
  .hw-kpis { grid-template-columns:repeat(auto-fit,minmax(105px,1fr)); }
  .hw-stat-val { font-size:1.4rem; }
}
@media (max-width: 720px) {
  .hw-page { padding:1rem 0.75rem 3rem; }
  .hw-controls { flex-direction:column; align-items:stretch; }
  .hw-controls select, .hw-controls input, .hw-btn-reset, .hw-mode-toggle { width:100%; }
  .hw-mode-toggle { display:flex; }
  .hw-mode-btn { flex:1; }
  .hw-count { margin-left:0; text-align:right; }
  .hw-grid { grid-template-columns:1fr; }
  .hw-status { grid-template-columns:repeat(3,1fr); }
}
@media (max-width: 420px) {
  .hw-kpis { grid-template-columns:repeat(2,1fr); }
}

/* Print-friendly */
@media print {
  .hw-controls, .hw-mode-toggle { display:none; }
  .hw-card { break-inside:avoid; border-color:#888 !important; }
  body { background:white !important; color:black !important; }
}
</style>
'''


# ─── JS for filters + mode toggle ──────────────────────────
EXTRA_JS = '''
<script>
(function(){
  const els = {
    search: document.getElementById('hw-search'),
    zone:   document.getElementById('hw-zone'),
    proto:  document.getElementById('hw-proto'),
    brand:  document.getElementById('hw-brand'),
    matter: document.getElementById('hw-matter'),
    auto:   document.getElementById('hw-auto'),
    energy: document.getElementById('hw-energy'),
    reset:  document.getElementById('hw-reset'),
    modeCards: document.getElementById('hw-mode-cards'),
    modeTable: document.getElementById('hw-mode-table'),
    viewCards: document.getElementById('hw-view-cards'),
    viewTable: document.getElementById('hw-view-table'),
    countNum: document.getElementById('hw-count-num'),
  };

  const cards = Array.from(document.querySelectorAll('.hw-card'));
  const rows  = Array.from(document.querySelectorAll('.hw-table tbody tr'));

  function applyFilter() {
    const q = (els.search.value || '').toLowerCase().trim();
    const z = els.zone.value;
    const p = els.proto.value;
    const b = els.brand.value;
    const m = els.matter.value;
    const a = els.auto.value;
    const e = els.energy.value;

    const matches = (el) => {
      if (z && el.dataset.zone !== z) return false;
      if (p && el.dataset.protocol !== p) return false;
      if (b && el.dataset.brand !== b) return false;
      if (m && el.dataset.matter !== m) return false;
      if (a && el.dataset.auto !== a) return false;
      if (e) {
        const v = el.dataset.energy;
        if (e === 'yes' && v !== 'yes' && v !== 'partial') return false;
        if (e === 'partial' && v !== 'partial') return false;
        if (e === 'no' && v !== 'no') return false;
      }
      if (q) {
        const blob = (el.dataset.search || '') + ' ' + (el.textContent || '').toLowerCase();
        if (!blob.includes(q)) return false;
      }
      return true;
    };

    let visible = 0;
    cards.forEach(c => {
      const ok = matches(c);
      c.classList.toggle('hw-hidden', !ok);
      // Only count primary (non-duplicate Matter/UNKNOWN section) cards
      if (ok && !c.classList.contains('hw-card-dup')) visible++;
    });
    let tableVisible = 0;
    rows.forEach(r => {
      const ok = matches(r);
      r.classList.toggle('hw-hidden', !ok);
      if (ok) tableVisible++;
    });
    // Hide empty sections (sections where all cards hidden)
    document.querySelectorAll('.hw-section').forEach(sec => {
      const visible = sec.querySelectorAll('.hw-card:not(.hw-hidden)').length;
      sec.style.display = visible === 0 ? 'none' : '';
    });

    const shown = els.viewCards.style.display !== 'none' ? visible : tableVisible;
    els.countNum.textContent = shown;
  }

  ['search','zone','proto','brand','matter','auto','energy'].forEach(k => {
    if (!els[k]) return;
    els[k].addEventListener(k === 'search' ? 'input' : 'change', applyFilter);
  });

  els.reset.addEventListener('click', () => {
    els.search.value = '';
    ['zone','proto','brand','matter','auto','energy'].forEach(k => { if(els[k]) els[k].value=''; });
    applyFilter();
  });

  function setMode(mode) {
    if (mode === 'cards') {
      els.viewCards.style.display = '';
      els.viewTable.style.display = 'none';
      els.modeCards.classList.add('hw-mode-active');
      els.modeCards.setAttribute('aria-pressed','true');
      els.modeTable.classList.remove('hw-mode-active');
      els.modeTable.setAttribute('aria-pressed','false');
    } else {
      els.viewCards.style.display = 'none';
      els.viewTable.style.display = '';
      els.modeTable.classList.add('hw-mode-active');
      els.modeTable.setAttribute('aria-pressed','true');
      els.modeCards.classList.remove('hw-mode-active');
      els.modeCards.setAttribute('aria-pressed','false');
    }
    applyFilter();
  }

  els.modeCards.addEventListener('click', () => setMode('cards'));
  els.modeTable.addEventListener('click', () => setMode('table'));

  // Initial
  applyFilter();
})();
</script>
'''


# ─── Stitch from index.html template ───────────────────────
index_html = INDEX_HTML.read_text(encoding='utf-8')
m_head_end = index_html.find('</head>')
m_nav_start = index_html.find('<header')
m_nav_end = index_html.find('</header>')
m_footer_start = index_html.rfind('<footer')
m_footer_end = index_html.rfind('</footer>')

head_block = index_html[:m_head_end]
head_block = re.sub(
    r'<title>[^<]+</title>',
    '<title>Kompletní hardware chytré domácnosti | SMART HOME Semily</title>',
    head_block, count=1)
head_block = re.sub(
    r'<meta name="description" content="[^"]+"',
    '<meta name="description" content="Přesný přehled '
    f'{total} zařízení v projektu SMART HOME Semily — '
    f'{n_zigbee}× Zigbee, {n_zwave}× Z-Wave, {n_matter}× Matter, {n_wifi+n_cast}× Wi-Fi/Cast. '
    'Generováno z live Homey REST exportu, read-only přístup, bez interních ID."',
    head_block, count=1, flags=re.IGNORECASE)
head_block = re.sub(
    r'<meta property="og:title" content="[^"]+"',
    '<meta property="og:title" content="Kompletní hardware chytré domácnosti | SMART HOME Semily"',
    head_block, count=1)
head_block = re.sub(
    r'<meta property="og:description" content="[^"]+"',
    f'<meta property="og:description" content="{total} zařízení, {len(physical_zones)} zón, '
    f'{len(by_proto)} protokolů včetně Matter ({n_matter}). Live Homey export."',
    head_block, count=1)

new_head = head_block + EXTRA_CSS + '\n</head>'
header_block = index_html[m_nav_start:m_nav_end + len('</header>')]
footer_block = index_html[m_footer_start:m_footer_end + len('</footer>')]


# ─── Body ───────────────────────────────────────────────────
BODY = f'''
<main class="hw-page">
  <div class="hw-hero">
    <h1>Kompletní hardware systému SMART HOME</h1>
    <p>Přesný přehled fyzických zařízení, senzorů, světel, audio prvků, měření a infrastruktury v bytě v Semilech. Generováno z live Homey REST exportu — <strong>žádné odhady, žádné fake položky</strong>.</p>
    <p class="hw-source-note">📊 Zdroj pravdy: <code>data/hardware_inventory_verified.json</code> · snapshot <code>{meta['date']}</code> · {total} zařízení, {len(physical_zones)} fyzických zón · poslední aktualizace <strong>{DATE}</strong></p>
    {KPI_BLOCK}
  </div>

  <div class="hw-note">
    <strong>🔒 Bezpečnost a transparentnost:</strong> Stránka <strong>nezobrazuje</strong>
    interní device ID (UUID), IP adresy, MAC adresy ani API tokeny. Zobrazena jsou
    pouze obecná data: název, výrobce, model, protokol, zóna, role, automatizace, měření energie.
    Kamery jsou zmíněné jen popisem role — stream není veřejný. Source-of-truth je živý Homey REST snapshot
    (read-only přístup, žádné PUT/POST), generován skriptem <code>_build_hardware_verified.py</code>.
  </div>

  {FILTERS_BLOCK}

  {CARDS_VIEW}

  {TABLE_VIEW}

  <section class="hw-section" id="sec-meta" style="margin-top:3rem;padding:1.2rem 1.4rem;background:rgba(255,255,255,0.03);border:1px solid rgba(255,255,255,0.08);border-radius:12px;">
    <h2 class="hw-section-h2" style="border:0;padding:0;font-size:1.05rem;">📊 Souhrnné metadata</h2>
    <p style="margin:0.6rem 0;font-size:0.86rem;opacity:0.85;">
      <strong>Protokoly:</strong> {", ".join(f"{p} ({c})" for p,c in by_proto.most_common())}
    </p>
    <p style="margin:0.6rem 0;font-size:0.86rem;opacity:0.85;">
      <strong>Ověření:</strong> {by_verif.get('verified',0)}× verified, {by_verif.get('partial',0)}× partial, {by_verif.get('unknown',0)}× unknown.
      Položky s <em>partial</em> stavem mají správný protokol + zónu + brand, ale chybí
      lokální fotka nebo přesný hardware model (např. konkrétní typ Lidl žárovky za Matter virtual bridge).
    </p>
    <p style="margin:0.6rem 0;font-size:0.86rem;opacity:0.85;">
      Pro hlubší audit viz <a href="HARDWARE_PAGE_AUDIT.md" style="color:#7cd6ff;">HARDWARE_PAGE_AUDIT.md</a> ·
      foto zdroje <a href="hardware_image_sources.csv" style="color:#7cd6ff;">hardware_image_sources.csv</a> ·
      data <a href="data/hardware_inventory_verified.json" style="color:#7cd6ff;">hardware_inventory_verified.json</a>.
    </p>
  </section>

</main>

{EXTRA_JS}
'''


# Compose final HTML
final = new_head + index_html[m_head_end + len('</head>'):m_nav_start] + \
    header_block + BODY + footer_block + \
    index_html[m_footer_end + len('</footer>'):]

OUT_HTML.write_text(final, encoding='utf-8')
print(f'OK hardware-komplet.html ({OUT_HTML.stat().st_size // 1024} KB)')
print(f'  Cards: {len(items)}')
print(f'  Sections: Matter ({len(matter_items)}) + Zones ({len(zones_present_ord)}) + Legacy ({len(legacy_items)}) + UNKNOWN ({len(unknown_items)})')
print(f'  Filters: 7 (search, zone, proto, brand, matter, auto, energy)')
print(f'  Mode toggle: Cards / Table')
